# Generated by Django 2.0.7 on 2018-08-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='invitation',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Pair')], default=0),
            preserve_default=False,
        ),
    ]
